volumes:
  grafana-storage: {}
  prom_data: {}

networks:
  monitoring-net: {}
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
     - grafana-storage:/var/lib/grafana
    networks:
      - monitoring-net
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - monitoring-net

  loki:
    image: grafana/loki:3.0.1                      
    container_name: loki 
    restart: unless-stopped                         
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki:/etc/loki
    ports:
      - "3100:3100"                                 
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - monitoring-net     

  promtail:
    image: grafana/promtail:3.0.0                  
    container_name: promtail
    volumes:                        
      - ./promtail-config.yaml:/mnt/config/promtail-config.yaml 
      - /var/log:/var/log  # host logs 
    depends_on:                           
      - loki                                      
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - monitoring-net